import type { Metadata } from "next";
import "./globals.css";
import DesktopSidebar from "@/app/components/DesktopSidebar";
import React from "react";
import MobileSidebar from "@/app/components/MobileSidebar";
import {DarkModeProvider} from "@/app/components/DarkModeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <DarkModeProvider>
            <body>
            <div className="flex flex-col min-h-screen">
                {/* Desktop Sidebar: visible on lg and above */}
                <div className="hidden lg:flex fixed top-0 left-0 w-64 h-full bg-gray-100 shadow-md">
                    <DesktopSidebar/>
                </div>
                {/* Mobile Sidebar: visible on sm and md */}
                <div className="block lg:hidden">
                    <MobileSidebar/>
                </div>
                <main className="flex-grow lg:ml-64 h-full">
                    {children}
                </main>
            </div>
            </body>
        </DarkModeProvider>
        </html>
    );
}